Css two column layout
Smith-Steve/c0321-code-solutions pull request #27
Opened 2021-03-17 02:59 UTC by Steve-A-Dore

I am not submitting this. I want to be able to look at and review the code on github while I am working on a different project, so I pushed it up. Did not know how else to do it. Sorry Cody - still requires touching up.

2021-03-18 20:04 UTC, codingcodymiller requested changes
Yo dude!! I know you still have this in progress, just wanted to give you a review so it's clear there are still changes needed. If you have any questions on how to tackle this, make sure you reach out in Slack!

2021-03-18 23:49 UTC, Steve-A-Dore commented
@codingcodymiller Hey Cody, didn't see your comment.. Sorry about that. I wanted to look at the code as I was going along. Won't let it happen again. Sorry.

![image](https://user-images.githubusercontent.com/51938797/111711849-ccfabe00-8809-11eb-9053-1310b7cda5b0.png)
I think this is pretty good, I think I'm catching on in CSS a little bit.

2021-03-19 17:49 UTC, codingcodymiller requested changes
Hey dude, nice progress!! Your button is not centered below the columns though, as in the example. Please get that fixed and resubmit and I will give a more thorough look

2021-03-22 05:10 UTC, Steve-A-Dore commented
![image](https://user-images.githubusercontent.com/51938797/111943219-38ef5780-8a92-11eb-9591-b305e5d14733.png)

2021-03-22 21:53 UTC, codingcodymiller requested changes

2021-03-22 21:53 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  bottom: 475px;
Try `text-align: center`. This should not require absolute positioning

2021-03-23 18:14 UTC, codingcodymiller approved these changes
Nice work!!

2021-03-24 01:16 UTC, merged