Css four column layout
Smith-Steve/c0321-code-solutions pull request #34
Opened 2021-03-19 03:22 UTC by Steve-A-Dore

![image](https://user-images.githubusercontent.com/51938797/111727192-a51a5300-8827-11eb-8478-206896c9cf3c.png)

2021-03-19 17:51 UTC, codingcodymiller requested changes
Great work so far!! please see my note

2021-03-19 17:51 UTC, codingcodymiller commented on css-four-column-layout/styles.css
> +  margin-top: -50px;
You definitely want to be avoiding negative values for margin and padding. If you feel the need for a negative margin, it is likely that there is another element you can just reduce the margin on.

2021-03-23 02:27 UTC, Steve-A-Dore commented
![image](https://user-images.githubusercontent.com/51938797/112083567-86c49800-8b44-11eb-9ffd-5d3f2105ba84.png)

I have made the requested changes, and was able to manage to get rid of the negative margin.

2021-03-23 18:14 UTC, codingcodymiller approved these changes

2021-03-24 01:17 UTC, merged